### ISSUE TITLE
failed initialization: this plugin requires at least V-REP 3.4.0 rev9

### ISSUE THREAD

**Issue by fferri** [CoppeliaRobotics/v_repExtRosInterface#18]
_From @xukuanHIT on August 14, 2017 10:25_

Hi, I complied succeedly, but it cannot be loaded when I start vrep ,the error is 
"Plugin 'RosInterface' : loading...
this plugin requires at least V-REP 3.4.0 rev9
Plugin 'RosInterface' : load failed (failed initialization)"
The vrep I used is newest, What should I do?

_Copied from original issue: fferri/v_repExtRosInterface#18_

**Comment by fferri** [comment]
Which version of V-REP are you using? You can see the version in the Help->About menu.

**Comment by fferri** [comment]
_From @xukuanHIT on August 15, 2017 3:53_

V-REP PRO EDU ,Version 3.4.0(rev.1) , Should I use rev9 ?

**Comment by fferri** [comment]
definitely yes

**Comment by fferri** [comment]
_From @xukuanHIT on August 15, 2017 4:2_

The newest version I can find is rev1, http://www.coppeliarobotics.com/downloads.html .Can you give me a website link where I can download it ? Thank you very much !

**Comment by fferri** [comment]
_From @Coppelia on August 15, 2017 6:41_

You can download rev. 9 from here: http://www.coppeliarobotics.com/files/tmp/

**Comment by fferri** [comment]
_From @xukuanHIT on August 16, 2017 8:58_

Thank you !

**Comment by padilla0** [comment]
hi, I have the same problem but i cant find the vrep rev9 in that link.   there is another place to download it?

**Comment by fferri** [comment]
V-REP 3.5.0 has been released.

Access the release here:
 
www.coppeliarobotics.com/downloads.html

**Comment by padilla0** [comment]
oh....true.....thanks a lot

**Comment by ganeshrk95** [comment]
Hi! I am using 3.5. I was able to build 

> libv_repExtRosInterface.so
But, I placed it inside the VREP parent folder replacing the older one. I still get initialization failed error.

**Comment by VinealShiloh** [comment]
Hi, I complied successfully, but when I start vrep ,i am getting this error 
**Verison :**  V-REP PLAYER V3.6.2. (rev. 0)
 
Plugin 'RosInterface': loading...
Error with plugin 'RosInterface': load failed (could not load). The plugin probably couldn't load dependency libraries. For additional infos, modify the script 'libLoadErrorCheck.sh', run it and inspect the output.
Plugin 'Vision': loading...
Plugin 'Vision': load succeeded.
Using the 'MeshCalc' plugin.

Can someone help me out here? Am i missing something


> V-REP 3.5.0 has been released.
> 
> Access the release here:
> 
> [www.coppeliarobotics.com/downloads.html](http://www.coppeliarobotics.com/downloads.html)
