### ISSUE TITLE
vrep_ros_interface cannot find package configuration file provided by VREP

### ISSUE THREAD

**Issue by fferri** [CoppeliaRobotics/v_repExtRosInterface#19]
_From @Spielzeug on September 21, 2017 12:20_

catkin build output: https://pastebin.com/hHApbTTq

 CMAKE_SOURCE_DIR is ~/catkin_ws/src, so CMAKE_MODULE_PATH evaluates to ~/catkin_ws/src/cmake/modules

_Copied from original issue: fferri/v_repExtRosInterface#19_

**Comment by h3ct0r** [comment]
This error is happening to me at the latest version; this was solved?

**Comment by fferri** [comment]
v_repExtRosInterface/cmake/modules is automatically added to CMAKE_MODULE_PATH.

I can not reproduce your issue.
Try starting from scratch, following the instructions at https://github.com/CoppeliaRobotics/v_repExtRosInterface/blob/master/README.md

**Comment by h3ct0r** [comment]
@fferri, Yes I have the FindVREP.cmake in my project (vrep_ros_interface/cmake/modules/FindVREP.cmake). 
I am using ROS Kinetic with Ubuntu 16.04.3, and I performed the git clone and catkin_make following the README instructions.

I am able to bypass the error by replacing CMAKE_SOURCE_DIR by CMAKE_CURRENT_SOURCE_DIR on the _CMakeLists.txt_, but now other errors arise:

`python: can't open file '/home/h3ct0r/catkin_ws/src/external/v_repStubsGen/generate.py': [Errno 2] No such file or directory
vrep_ros_interface/CMakeFiles/v_repExtRosInterface.dir/build.make:61: recipe for target 'generated/stubs.cpp' failed
make[2]: *** [generated/stubs.cpp] Error 2
CMakeFiles/Makefile2:12780: recipe for target 'vrep_ros_interface/CMakeFiles/v_repExtRosInterface.dir/all' failed
make[1]: *** [vrep_ros_interface/CMakeFiles/v_repExtRosInterface.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`
