### ISSUE TITLE
How to create the file libv_repExtRosInterface.so

### ISSUE THREAD

**Issue by EdnilsonAraujo** [CoppeliaRobotics/v_repExtRosInterface#21]
I'm trying to use V-REP and ROS Kinetic but I'm finding it difficult to create the file libv_repExtRosInterface.so. The instructions in readme.md are a bit confusing for me. Can you detail the instructions so that I can better understand?

**Comment by fferri** [comment]
Doesn't work that way.

You're going to need to explain what steps did you try, and how that failed, i.e. you can post here console output, a description of what happened, and anything that can be useful to reproduce your problem.

**Comment by EdnilsonAraujo** [comment]
Hi, I clone the project into a catkin work space but when I compiled I got an error message:
-- +++ processing catkin package: 'vrep_ros_interface'
-- ==> add_subdirectory(vrep_ros_interface)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at vrep_ros_interface/CMakeLists.txt:11 (find_package):
  By not providing "FindVREP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VREP", but
  CMake did not find one.

  Could not find a package configuration file provided by "VREP" with any of
  the following names:

    VREPConfig.cmake
    vrep-config.cmake

  Add the installation prefix of "VREP" to CMAKE_PREFIX_PATH or set
  "VREP_DIR" to a directory containing one of the above files.  If "VREP"
  provides a separate development package or SDK, be sure it has been
  installed.
-- Configuring incomplete, errors occurred!
See also "/home/ednilson/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ednilson/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:1102: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
I do not know what I'm doing wrong.

**Comment by fferri** [comment]
Looks the same as CoppeliaRobotics/v_repExtRosInterface#19

**Comment by EdnilsonAraujo** [comment]
I already have the xsltproc installed as h3ct0r suggests. I created a new workspace (ros_ws) and cloned the directory (git clone --recursive https://github.com/CoppeliaRobotics/v_repExtRosInterface.git vrep_ros_interface).
I still have the same error:
ednilson @ ednilson-desktop: ~ / vrep_ws $ catkin_make
Base path: / home / ednilson / vrep_ws
Source space: / home / ednilson / vrep_ws / src
Build space: / home / ednilson / vrep_ws / build
Devel space: / home / ednilson / vrep_ws / devel
Install space: / home / ednilson / vrep_ws / install
####
#### Running command: "make cmake_check_build_system" in "/ home / ednilson / vrep_ws / build"
####
- Using CATKIN_DEVEL_PREFIX: / home / ednilson / vrep_ws / devel
- Using CMAKE_PREFIX_PATH: / home / ednilson / catkin_ws / devel; / opt / ros / kinetic
- This workspace overlays: / home / ednilson / catkin_ws / devel; / opt / ros / kinetic
- Using PYTHON_EXECUTABLE: / usr / bin / python
- Using Debian Python package layout
- Using empy: / usr / bin / empy
- Using CATKIN_ENABLE_TESTING: ON
- Call enable_testing ()
- Using CATKIN_TEST_RESULTS_DIR: / home / ednilson / vrep_ws / build / test_results
- Found gtest sources under '/ usr / src / gtest': gtests will be built
- Using Python nosetests: /usr/bin/nosetests-2.7
- catkin 0.7.6
- BUILD_SHARED_LIBS is on
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~
- ~~ traversing 1 packages in topological order:
- ~~ - vrep_ros_interface
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~
- +++ processing catkin package: 'vrep_ros_interface'
- ==> add_subdirectory (vrep_ros_interface)
- Using these message generators: gencpp; geneus; genlisp; gennodejs; genpy
CMake Error at vrep_ros_interface / CMakeLists.txt: 11 (find_package):
  By not providing "FindVREP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VREP", but
  CMake did not find one.

  Could not find a package configuration file provided by "VREP" with any of
  the following names:

    VREPConfig.cmake
    vrep-config.cmake

  Add the installation prefix of "VREP" to CMAKE_PREFIX_PATH or set
  "VREP_DIR" to a directory containing one of the above files. If "VREP"
  provide a separate development package or SDK, be sure it has been
  installed.


- Configuring incomplete, errors occurred!
See also "/home/ednilson/vrep_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ednilson/vrep_ws/build/CMakeFiles/CakeError.log".
Makefile: 290: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
ednilson @ ednilson-desktop: ~ / vrep_ws $

**Comment by EdnilsonAraujo** [comment]
Hi, Ferri. I was forgetting to set the V-REP installation path (export VREP_ROOT = ~ / path / to / v_rep / folder)
Finally I had to download revision 19.
Now it's working. Thank you for your help !
