### ISSUE TITLE
Catkin build fails

### ISSUE THREAD

**Issue by AnselmC** [CoppeliaRobotics/v_repExtRosInterface#23]
Hi,
I'm not sure this is the right place for this, but anyhow:
When cloning this repo into catkin_ws/src and then executing catkin build I get the following error:

> Errors     << vrep_ros_interface:check /home/parallels/catkin_ws/logs/vrep_ros_interface/build.check.001.log
CMake Error at /home/parallels/catkin_ws/src/vrep_ros_interface/CMakeLists.txt:53 (add_library):
  Cannot find source file:

    /home/parallels/catkin_ws/src/vrep_ros_interface/external/v_repPlusPlus/Plugin.cpp

 

> Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

> CMake Error: CMake can not determine linker language for target: v_repExtRosInterface

> CMake Error: Cannot determine link language for target "v_repExtRosInterface".
make: *** [cmake_check_build_system] Error 1

This seems to be due to the fact that the external/v_repPlusPlus folder (and external/v_repStubsGen) is empty. Any idea why this is the case and how to resolve the issue?

Thanks,
Anselm

**Comment by fferri** [comment]
Yes, you didn’t follow README instructions. You have to checkout submodules or clone repo recursively.
