### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by deokisys** [CoppeliaRobotics/v_repExtRosInterface#24]
I install xsltproc
`sudo apt install xsltproc`

**Comment by fferri** [comment]
What build error?

Please submit a proper bug report and reopen.

**Comment by deokisys** [comment]
`$ mkdir -p catkin_build_ws/src`
`$   cd catkin_build_ws/src`
`$ git clone --recursive https://github.com/CoppeliaRobotics/v_repExtRosInterface.git vrep_ros_interface`
`$ echo "export VREP_ROOT=~/vrep" >> ~/.bashrc`
`$ source ~/.bashrc`
`$ cd ~/catkin_build_ws`
`$ catkin build`



error message

> [build] Found '1' packages in 0.0 seconds.                                     
> [build] Updating package table.                                                
> Starting  >>> catkin_tools_prebuild                                            
> Finished  <<< catkin_tools_prebuild                [ 1.5 seconds ]             
> Starting  >>> vrep_ros_interface                                               
> _______________________________________________________________________________
> Errors     << vrep_ros_interface:make /home/ailab/catkin_build_ws/logs/vrep_ros_interface/build.make.000.log
> Traceback (most recent call last):
>   File "/home/ailab/catkin_build_ws/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 96, in <module>
>     runprogram('xsltproc', '-o', output('reference.html'), rel('xsl/reference.xsl'), input_xml)
>   File "/home/ailab/catkin_build_ws/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 50, in runprogram
>     runsubprocess(what, [what] + list(args))
>   File "/home/ailab/catkin_build_ws/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 38, in runsubprocess
>     child = subprocess.Popen(args)
>   File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> make[2]: *** [generated/stubs.cpp] Error 1
> make[2]: *** Deleting file 'generated/stubs.cpp'
> make[1]: *** [CMakeFiles/v_repExtRosInterface.dir/all] Error 2
> make: *** [all] Error 2
> cd /home/ailab/catkin_build_ws/build/vrep_ros_interface; catkin build --get-env vrep_ros_interface | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
> ...............................................................................
> Failed     << vrep_ros_interface:make              [ Exited with code 2 ]      
> Failed    <<< vrep_ros_interface                   [ 5.4 seconds ]             
> [build] Summary: 1 of 2 packages succeeded.                                    
> [build]   Ignored:   None.                                                     
> [build]   Warnings:  None.                                                     
> [build]   Abandoned: None.                                                     
> [build]   Failed:    1 packages failed.                                        
> [build] Runtime: 6.9 seconds total.                                            
> [build] Note: Workspace packages have changed, please re-source setup files to use them.
>



require 
` sudo apt install xsltproc`
