### ISSUE TITLE
Is it possible to cross-compile for macOS/Windows?

### ISSUE THREAD

**Issue by berezovskyi** [CoppeliaRobotics/v_repExtRosInterface#28]
We are experiencing performance issues with V-REP running under Virtualbox Ubuntu VMs. To mitigate the effect, we are trying to run V-REP on the host machine, where we have full 3D acceleration, while running ROS components under a VM.

So far we managed to access ROS master running under an Ubuntu VM in Virtualbox from the macOS host via an SSH tunnel and a Host-only Virtualbox adaptor.

The next step is to load the V-REP `RosInterface` plugin, but if we compile it with catkin under Ubuntu, we get a shared module which won't be possible to load from macOS.

Could you please assist / advise us how to cross-compile the plugin as a macOS `.dylib` dynamic library and/or a Windows library, please?

**Comment by fferri** [comment]
If you want to load the plugin on macOS, just install ROS on macOS and compile the plugin from there. ROS on macOS is not officially supported, but there are many people who did it and you can find several notes/blog posts describing the steps.

Cross-compiling would not work in this case unless you also cross-compile all the dependencies, which can be a pain.

Please use the [CoppeliaRobotics forum](http://www.forum.coppeliarobotics.com) for questions and support.
