### ISSUE TITLE
Build error - simSetModuleInfo was not declared in this scope

### ISSUE THREAD

**Issue by drfastolfe** [CoppeliaRobotics/v_repExtRosInterface#30]
Followed all the instruction to clone and build the package, and installed xsltproc. I am trying to build this with ROS Kinetic on Ubuntu 16.04.
However when I use catkin_make, the build fails with the error 'simSetModuleInfo' was not declared in this scope in vrep_ros_interface.cpp

**Comment by fferri** [comment]
You need V-REP 3.5.0. Please reopen & comment if the issue persists.
