### ISSUE TITLE
failed initialization: in V-REP 3.6.2 rev0

### ISSUE THREAD

**Issue by VinealShiloh** [CoppeliaRobotics/v_repExtRosInterface#34]
Hi all, i am to complie successfully but when i am running i am getting this error
Plugin 'RosInterface': loading...
Error with plugin 'RosInterface': load failed (could not load). The plugin probably couldn't load dependency libraries. For additional infos, modify the script 'libLoadErrorCheck.sh', run it and inspect the output.
Plugin 'Vision': loading...
Plugin 'Vision': load succeeded.
 Can anyone help me out here? Am i doing something wrong/missing

**Comment by fferri** [comment]
Please use the [forum](http://www.forum.coppeliarobotics.com) for support requests.
