### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by ghx-0228** [CoppeliaRobotics/v_repExtRosInterface#35]
Hi, when I catkin build the "ros-interface", I encountered the following problem. Could you help me solve it.
![image](https://user-images.githubusercontent.com/47413096/66063147-616d5400-e575-11e9-9212-a3e9eeed8d22.png)

**Comment by fferri** [comment]
Cannot reproduce here.

Please fully describe the steps you do, from cloning the repository to getting the error, and reopen this issue.

Thanks.
